spring:
    application: 
        name: configurationprts
    profiles:
        active: prod

# greeting:
#     welcome: Welcome to ${spring.application.name}

name:
    manager:
        size: 45

server:
    port: 9090

