spring:
    application:
        name: mongodb
    data:
        mongodb:
            host: localhost
            port: 27017
            database: mongotestdb
            repositories:
                type: auto

server:
    port: 9090
